---
- name: Delete VM Snapshot
  hosts: localhost
  gather_facts: false

  vars:
    vergeos_host: "{{ lookup('env', 'VERGEOS_HOST') | default('vergeos.example.com', true) }}"
    vergeos_username: "{{ lookup('env', 'VERGEOS_USERNAME') | default('admin', true) }}"
    vergeos_password: "{{ lookup('env', 'VERGEOS_PASSWORD') }}"
    vergeos_insecure: "{{ lookup('env', 'VERGEOS_INSECURE') | default(true) }}"

  tasks:
    - name: Validate required variables
      ansible.builtin.assert:
        that:
          - snapshot_id is defined
        fail_msg: "snapshot_id must be provided via -e (e.g., -e snapshot_id=123)"

    - name: Delete snapshot by ID
      vergeio.vergeos.vm_snapshot:
        host: "{{ vergeos_host }}"
        username: "{{ vergeos_username }}"
        password: "{{ vergeos_password }}"
        insecure: "{{ vergeos_insecure }}"
        snapshot_id: "{{ snapshot_id }}"
        state: absent
      when: snapshot_id is defined
      register: delete_result

    - name: Display deletion result
      ansible.builtin.debug:
        msg: |
          ========================================
          Snapshot Deleted Successfully
          ========================================
          Snapshot ID: {{ snapshot_id | default('N/A') }}
          Operation: {{ delete_result.operation | default('N/A') }}
