---
- name: Test VergeOS Dynamic Inventory
  hosts: all
  gather_facts: false

  tasks:
    - name: Display inventory information
      ansible.builtin.debug:
        msg: |
          ========================================
          Host: {{ inventory_hostname }}
          ========================================
          VM ID: {{ vergeos_vm_id | default('N/A') }}
          VM Name: {{ vergeos_name | default('N/A') }}
          Description: {{ vergeos_description | default('N/A') }}
          Status: {{ vergeos_status | default('N/A') }}
          CPU Cores: {{ vergeos_cpu_cores | default('N/A') }}
          RAM: {{ vergeos_ram | default('N/A') }} MB
          OS Family: {{ vergeos_os_family | default('N/A') }}
          Machine Type: {{ vergeos_machine_type | default('N/A') }}
          Machine ID: {{ vergeos_machine | default('N/A') }}

          Node: {{ vergeos_node_name | default('N/A (stopped)') }}
          Cluster: {{ vergeos_cluster | default('N/A') }}
          Tenant: {{ vergeos_tenant | default('N/A') }}

          IP Address: {{ vergeos_ip | default('N/A') }}
          MAC Addresses: {{ vergeos_mac_addresses | default([]) | join(', ') or 'N/A' }}
          Drives: {{ vergeos_drives | default([]) | length }} attached

          Created: {{ vergeos_created | default('N/A') }}
          Modified: {{ vergeos_modified | default('N/A') }}
          Tags: {{ vergeos_tags | default([]) | join(', ') or 'None' }}

          Groups: {{ group_names | join(', ') }}

- name: Show VMs by Status
  hosts: localhost
  gather_facts: false

  tasks:
    - name: List running VMs
      ansible.builtin.debug:
        msg: "Running VMs: {{ groups['status_running'] | default([]) | length }}"
      when: "'status_running' in groups"

    - name: List stopped VMs
      ansible.builtin.debug:
        msg: "Stopped VMs: {{ groups['status_stopped'] | default([]) | length }}"
      when: "'status_stopped' in groups"

- name: Show VMs by Node
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Display node groups
      ansible.builtin.debug:
        msg: |
          Available Node Groups:
          {% for group in groups.keys() | select('match', '^node_.*') %}
          - {{ group }}: {{ groups[group] | length }} VMs
          {% endfor %}
      when: groups.keys() | select('match', '^node_.*') | list | length > 0

- name: Show VMs by Cluster
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Display cluster groups
      ansible.builtin.debug:
        msg: |
          Available Cluster Groups:
          {% for group in groups.keys() | select('match', '^cluster_.*') %}
          - {{ group }}: {{ groups[group] | length }} VMs
          {% endfor %}
      when: groups.keys() | select('match', '^cluster_.*') | list | length > 0
